// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: JustScreenNMotor

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void MoveFixtureDown(lv_event_t * e);
void MoveFixtureUp(lv_event_t * e);
void StopWinding(lv_event_t * e);
void StartWinding(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
