// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: JustScreenNMotor

#include "ui.h"

// void MoveFixtureDown(lv_event_t * e)
// {
// 	// Your code here
// }

// void MoveFixtureUp(lv_event_t * e)
// {
// 	// Your code here
// }

// void StopWinding(lv_event_t * e)
// {
// 	// Your code here
// }

// void StartWinding(lv_event_t * e)
// {
// 	// Your code here
// }
