// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: JustScreenNMotor

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_MoveDown = NULL;
lv_obj_t * ui_MoveUp = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_NumberOfWindes = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_StopMoving = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_StartAddWindes = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_MoveDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        MoveFixtureDown(e);
    }
}

void ui_event_MoveUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        MoveFixtureUp(e);
    }
}

void ui_event_StopMoving(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        StopWinding(e);
        _ui_flag_modify(ui_MoveDown, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MoveUp, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_StartAddWindes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        StartWinding(e);
        _ui_flag_modify(ui_MoveDown, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MoveUp, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    //lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 125);
    lv_obj_set_height(ui_Panel1, 250);
    lv_obj_set_x(ui_Panel1, -140);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MoveDown = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_MoveDown, 100);
    lv_obj_set_height(ui_MoveDown, 100);
    lv_obj_set_x(ui_MoveDown, 0);
    lv_obj_set_y(ui_MoveDown, 60);
    lv_obj_set_align(ui_MoveDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MoveDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_MoveDown, &ui_img_blue_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveUp = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_MoveUp, 100);
    lv_obj_set_height(ui_MoveUp, 100);
    lv_obj_set_x(ui_MoveUp, 0);
    lv_obj_set_y(ui_MoveUp, -60);
    lv_obj_set_align(ui_MoveUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MoveUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_MoveUp, &ui_img_up_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 125);
    lv_obj_set_height(ui_Panel2, 250);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NumberOfWindes = lv_roller_create(ui_Panel2);
    lv_roller_set_options(ui_NumberOfWindes,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_NumberOfWindes, 100);
    lv_obj_set_height(ui_NumberOfWindes, 200);
    lv_obj_set_align(ui_NumberOfWindes, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_NumberOfWindes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumberOfWindes, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 125);
    lv_obj_set_height(ui_Panel3, 250);
    lv_obj_set_x(ui_Panel3, 150);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StopMoving = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_StopMoving, 100);
    lv_obj_set_height(ui_StopMoving, 100);
    lv_obj_set_x(ui_StopMoving, 0);
    lv_obj_set_y(ui_StopMoving, 60);
    lv_obj_set_align(ui_StopMoving, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopMoving, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StopMoving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopMoving, lv_color_hex(0xF43C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopMoving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_StopMoving);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Stop");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartAddWindes = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_StartAddWindes, 100);
    lv_obj_set_height(ui_StartAddWindes, 100);
    lv_obj_set_x(ui_StartAddWindes, 0);
    lv_obj_set_y(ui_StartAddWindes, -60);
    lv_obj_set_align(ui_StartAddWindes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartAddWindes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartAddWindes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_StartAddWindes);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Start");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MoveDown, ui_event_MoveDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveUp, ui_event_MoveUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopMoving, ui_event_StopMoving, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartAddWindes, ui_event_StartAddWindes, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_MoveDown = NULL;
    ui_MoveUp = NULL;
    ui_Panel2 = NULL;
    ui_NumberOfWindes = NULL;
    ui_Panel3 = NULL;
    ui_StopMoving = NULL;
    ui_Label1 = NULL;
    ui_StartAddWindes = NULL;
    ui_Label2 = NULL;

}
