// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: JustScreenNMotor

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern void ui_event_MoveDown(lv_event_t * e);
extern lv_obj_t * ui_MoveDown;
extern void ui_event_MoveUp(lv_event_t * e);
extern lv_obj_t * ui_MoveUp;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_NumberOfWindes;
extern lv_obj_t * ui_Panel3;
extern void ui_event_StopMoving(lv_event_t * e);
extern lv_obj_t * ui_StopMoving;
extern lv_obj_t * ui_Label1;
extern void ui_event_StartAddWindes(lv_event_t * e);
extern lv_obj_t * ui_StartAddWindes;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

